### ISSUE TITLE
[RFC] Proposal for Container Metadata Validation

### ISSUE THREAD

**Issue by mingweishih** [confidential-containers/confidential-containers#126]
# Authors

- [Ming-Wei Shih](https://github.com/mingweishih) mishih@microsoft.com
- [Dan Mihai](https://github.com/danmihai1) dmihai@microsoft.com

# Introduction

An area to improve the security of the current CoCo design is container metadata validation (see confidential-containers/confidential-containers#124). According to the [OCI runtime specification](https://github.com/opencontainers/runtime-spec/blob/main/config.md), the container metadata is specified by the configuration file, or `config.json`, in the OCI bundle. In the current CoCo implementation, `kata-agent` receives the `config.json` as part of the `CreateContainerRequest` from `kata-shim` and uses the `config.json` (with minor modifications) to create a container via `rustjail`. The resulting container includes metadata, such as process arguments, environment variables, and mount points, as described in the `config.json`. Given that the orchestration operator is untrusted in the CoCo threat model, the attacker has full control over the `config.json` before sending it to `kata-agent`. Without validations, `kata-agent` may create a container with a tampered `config.json`, resulting in unwanted container behaviors. The situation is particularly concerning in the Kubernetes end-to-end scenario where the user typically expects the container metadata to match [PodSpec](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#PodSpec) or [PodTemplateSpec](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-template-v1/#PodTemplateSpec) in the `yaml` file. 

# Design

The goal of the design is to allow users to specify a policy that validates the container metadata. To ensure the integrity and trustworthiness of the policy, the design leverages the *host data* feature from hardware TEEs and integrates the feature into the current remote attestation process. The rest of the section gives an overview of the high-level design and then details each part of the design.

## Overview

This section provides a walk-through of the design based on the figure as shown below.

<img width="584" alt="container_meatadata_validation_large" src="https://user-images.githubusercontent.com/58993167/203188927-b1179f49-8753-4840-9bdf-d1fb8972a100.png">

1. A user writes a policy (or using the `yaml` file itself) that describes rules he or she wants to enforce against the specific fields of the container metadata in a trusted environment (section `Policy Generation`).
2. The user sets the policy digest as the custom attestation rule.
3. The user deploys a pod to the cloud via `kubectl` using the `yaml` file along with the policy (section `Policy Passing`).
4. During the VM creation, `kata-shim` passes the policy digest to the hypervisor, which is responsible to forward the digest as the `host data` to the TEE hardware (section `Policy Attestation`).
5. The trustworthiness of the policy is established by the user via the attestation process, based on the `host data` from the attestation report (section `Policy Attestation`).
6. Upon receiving a `CreateContainerRequest`, `kata-agent` validates the integrity of the host-passed policy by computing the digest of the policy and comparing it against the `host data` in the TEE attestation evidence (section `Policy Attestation`).
7. (optional) If the host-passed policy is a `yaml` file, `kata-agent` converts the `yaml` file to the policy (section `Policy Generation`).
8. `kata-agent` enforces the policy against the host-passed `config.json` (section `Policy Enforcement`).
9. If the policy enforcement passes, `kata-agent` proceeds with the container creation. Otherwise, `kata-agent` returns an error and aborts.

## Policy Format

The format of a policy should support rules against the metadata (`config.json`) of multiple containers within a pod (`yaml` file). The design defines a policy as a list of key-value pairs (see below), where the key is a unique `container id` and the value is the associated `container policy`.

```
"containers": {
  "CONTAINER_1_ID": <CONTAINER_1_POLICY>,
  "CONTAINER_2_ID": <CONTAINER_2_POLICY>,
  ...
}
```
- `container id`

  A `container id` should be unique, supporting `container policy` lookup for the corresponding container. Options for the `container id` include:
  - container name (`container.name` in a `yaml` file)

    The uniqueness of the container name is enforced by Kubernetes. However, this option does not guarantee strong linking because the container name is still passed by the host (e.g., the `io.kubernetes.cri.container-name` annotation). For example, the host can swap the names between two container policies (while, in most cases, resulting in a mismatch in container policy).

  - The order of container creation

    Kubernetes creates the containers based on the order in each container that appears in the `yaml` file (with `initContainers` taking precedence over `containers`), which guarantees the uniqueness of the index. Using the index also ensures the order of the container creation is as expected. At the same time, this option may cause lookup issues with the pod update (e.g., only selective containers will be re-created).

- `container policy`

  An intuitive option for a `container policy` is `OCI runtime specification`; i.e., a `container policy` is effectively a user-expected `config.json`. However, users may not be able to determine some expected values in a `config.json` based on a `yaml` file before the pod deployment. Examples include:
  - Environment variables with `envFrom` or `valueFrom` that uses [Pod fields](https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/#use-pod-fields-as-values-for-environment-variables) (e.g., `status.PodIP`) or `Secret` as references.
  - Source of `volumeMount` which may be patched by `kata-shim` and includes random bytes.

  The design addresses this issue by supporting both string- and regular-expression-based rules for fields when necessary. Examples include (the list may grow)
  - `process.env`

    `yaml` file
    ```
    env:
    - name: POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    ```

    `container policy`
    ``` 
      "process": {
        "env": [
          "POD_IP=^((25[0-5]|(2[0-4]|1\\d|[1-9]|)\\d).?\\b){4}$"
        ]
      }
      ```

  - `mounts[n].source`

    `yaml` file
    ```
      volumeMounts:
      - name: host-empty-vol
        mountPath: "/host/cache"
      ...
    volumes:
    - name: host-empty-vol
      emptyDir: {}
    ```

    `config.json`
    ```
    "mounts": [
      {
        "destination": "/host/cache",
        "type": "local",
        "source": "^/run/kata-containers/.+"
        "options": [
          "rbind",
          "rprivate",
          "rw"
        ]
      }
    ]
    ```

## Policy Generation

An important design requirement is allowing users to derive a policy from a `yaml` file used for pod deployment; i.e., users should be able to determine the expected digest of the policy and set the custom attestation rule before the pod deployment. However, according to the Kubernetes end-to-end scenario (based on `containerd`), using a `yaml` file alone is insufficient to generate the `config.json`. The gaps include:

1. Syntax gap: The syntaxes between a `yaml` file and a `config.json` do not have one-to-map mapping. For example, a `volmueMount` from a `yaml` file does not have corresponding fields for `type` and `source`, and `options` in a `mount` from a `config.json`.

2. Input gap: The derivation of a `config.json` takes not only a `yaml` file as an input. Other inputs include
   - [OCI image configurations](https://github.com/opencontainers/image-spec/blob/main/config.md) of each container image specified in the `yaml` file.
   - Infrastructure (e.g., `kubelet`, `containerd`, `kata-shim`) injections and modifications. For example:
     - `yaml` file patched by [mutating admission webhooks](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#mutatingadmissionwebhook)
     - [Environment variables](https://kubernetes.io/docs/concepts/services-networking/service/#environment-variables) added by `kubelet`
     - [Default Spec](https://github.com/containerd/containerd/blob/release/1.6/oci/spec.go#L132) added by `containerd`
     - Mount source patched by [kata-shim](https://github.com/kata-containers/kata-containers/blob/stable-3.0/src/runtime/virtcontainers/kata_agent.go#L869)

To close the gaps, the design proposes the following solutions
- `infrastructure rules`

  A list of hard-coded rules that capture infrastructure-related values in a `config.json` (see `Appendix` for an example).

- Policy generation library (or tool)

  A library or a tool that takes a `yaml` file, a list of OCI image configurations, and the `infrastructure rules` as inputs, processes each input (e.g., converting the `yaml` file to a `config.json`-compatible form), and generates the policy.

### User Experience

Depending on how a user involves in policy generation, the implementation of the above solutions varies.

1. Pre-deployment policy generation

   A user is responsible for generating a policy by utilizing the **policy generation tool** and passing the policy to `kata-agent` during the pod deployment. Also, the user needs to set the expected hash of the policy as the custom attestation rule. For each infrastructure update that changes the infrastructure rules, the user needs to re-generate the policy with the latest infrastructure rules and updates the custom rule. The cloud provider can provide an update to the policy generation tool to simplify the process.

2. Post-deployment policy generation with user inputs

   A user is responsible for passing inputs, including the `yaml` file itself and the infrastructure rules, to the `kata-agent` during the pod deployment. Accordingly, the user needs to set the expected hashes of both inputs as the custom attestation rule. During the pod creation, `kata-agent` uses the **policy generation library** to generate the policy based on the user inputs and OCI image configurations obtained from `image-rs`. For each infrastructure update, the user needs to provide only the latest infrastructure rules and updates the custom rule.

3. Post-deployment policy generation with hybrid inputs

   This design is similar to the previous one but offloads the infrastructure rules fetching to `kata-agent`. More specifically, `kata-agent` only receives the `yaml` file   from a user and fetches the infrastructure rules from a KBS or the cloud provider. Optionally, the user can specify how the infrastructure rules should be fetched (e.g., a URL). Therefore, the user does not need to take action for each infrastructure update (i.e., handled by the KBS or the cloud provider).

The following table summarizes the three cases in terms of
- Policy transparency: The level of understanding of the policy compared to the user inputs.
- Deployment Experience: The level of effort a user needs to make before the pod deployment
  (e.g., preparing user inputs and setting the custom rule).
- Update Experience: The level of effort a user needs to make after an infrastructure update
  (e.g., updating the user inputs and the custom rule).

| Policy Generation Type | Policy Transparency | Deployment Experience | Update Experience |
| ----------------- | --- |----------------- | -- |
| Pre-deployment | High | Low | Low |
| Post-deployment with user inputs | Medium | Medium | Medium |
| Post-deployment with hybrid inputs | Low | High | High | 

## Policy Passing

The requirement of the design is allowing a user to forward the policy or necessary inputs to `kata-agent` during the pod deployment. An idea that has the minimum impact on the existing pod deployment flow is passing the policy (or inputs) along with the `yaml` file via `kubectl`. The design proposes two options, both of which are based on [Pod annotations](https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/) and uses the key based on existing `io.katacontainers` (according to [Kata Configuration Annotations](https://github.com/kata-containers/kata-containers/blob/main/docs/how-to/how-to-set-sandbox-config-kata.md#kata-configuration-annotations)).

- Passing the encoded policy

  A simple approach is passing the policy with `base64` encoding as in the following example.

  Pre-deployment policy generation
  ```
  apiVersion: v1
  kind: Pod
  metadata:
    name: test-pod
    annotations:
      io.katacontainers.cc_policy: <base64-encoded policy>
  ```

  Post-deployment policy generation with user inputs
  ```
  apiVersion: v1
  kind: Pod
  metadata:
    name: test-pod
    annotations:
      io.katacontainers.pod_spec: <base64-encoded string>
      io.katacontainers.infrastructure_rules: <base64-encoded string>
  ```

  Note that while the size limitation of total annotations ([256 KB](https://github.com/kubernetes/kubernetes/pull/16068)) is sufficient for a policy, this approach inevitably bloats the size of the `yaml` file, decreasing its readability.

- Passing the URI

  To avoid bloating the `yaml` file, an approach is uploading the policy to a URI and passing the URI using the annotation (as shown below). However, this approach requires modifications in `kata-shim` to pull down the policy. The approach also imposes requirements on both the infrastructure (i.e., the ability to access the endpoint) and users (i.e., maintenance cost for the endpoint).
  
  Pre-deployment policy generation
  ```
  apiVersion: v1
  kind: Pod
  metadata:
    name: test-pod
    annotations:
      io.katacontainers.cc_policy_uri: <uri>
  ```

## Policy Attestation

To guarantee the integrity of the policy or user inputs, the design proposes to leverage the host data feature of the TEE hardware as described in [[RFC] Init Time Configuration for image-rs](https://github.com/confidential-containers/image-rs/issues/34). The following table summarizes the feature support from the relevant TEEs.

| TEE Type | Host Data | Interface for Passing Host Data|
| -------- | ----------------- | --- |
| `SEV_SNP` | `HOST_DATA` (32 bytes) | `SNP_LAUNCH_FINISH` |
| `TDX`     | `MRCONFIGID` (48 bytes) | `TDH.MNG.INIT` |
| `SGX`     | `CONFIGID` (64 bytes) | `EINIT` |

The feature allows the host to pass data during the TEE instance initialization without affecting the measurement of the instance. The TEE records and keeps the host data through the lifetime of the instance. In addition, the TEE includes the host data in the attestation report, allowing the verifier or relying party to validate the value during the attestation process.

### Host Data Scheme

Given that the size of the policy varies, the idea is passing only the fixed-length digest of the policy (e.g., a `sha-2` hash) as part of the host data to the TEE hardware while passing the full-sized policy to the `kata-agent`. To accommodate multiple inputs (e.g., a `yaml` file and the infrastructure rules), the host data can have a scheme that hosts digests for each input.

### Host Data Validation

Upon receiving a `CreateContainerRequest`, the `kata-agent` (`rpc::AgentService::do_create_container`) extracts the policy from the `config.json` (`oci`) passed by the host. Next, the `kata-agent` validates the policy by computing its hash and comparing the hash against the corresponding host data from the TEE attestation evidence. Once the validation passes, the `kata-agent` can proceed with the policy enforcement using the policy.

## Policy Enforcement

The key assumption of the policy enforcement design is that `rustjail` respects the `config.json` passed by `kata-agent` when initializing the container metadata. That is, by enforcing checks against the `config.json` before passing it to the `rustjail`, the design catches any unwanted modification made by the host. More concretely, the design proposes adding a module, `cc-policy-enforcer` (tentative), that takes a policy and a `config.json` as inputs and enforces the policy against the
`config.json`. The module can be used as a rust `crate` or runs as a gRPC server and plugged into the `kata-agent`. Similar to [attestation-service](https://github.com/confidential-containers/attestation-service), the module provides a plugin interface that supports various types of policy engines. Examples of plugins include

- Rust-based implementation

  Using `rust` is straightforward given that the rules are relatively simple and stable. In addition, the implementation can potentially take advantage of the existing `oci` crate.

- [OPA](https://www.openpolicyagent.org/)

  `OPA` is an ideal candidate to implement the policy enforcer given that it is widely used in the container space and has rich features. However, using `OPA` in CoCo comes with a few drawbacks:
  - The `go`-based implementation introduces extra complexity to the `CoCo` architecture
  - The policy format needs to be [Rego](https://www.openpolicyagent.org/docs/latest/policy-language/)
  - `Rego` itself also adds complexity to the project, increasing the maintenance efforts over time

The policy enforcement works as follows:

1. After validating the policy (during the `rpc::AgentService::do_create_container` call), the `kata-agent` passes the policy and the `config.json` to the module.
2. The module looks up the container policy based on the container id from the policy. Take using the container name as id, for example, the module can find the name in the `io.kubernetes.cri.container-name` annotation. Note that, if no container name is found, the module will use a hard-coded name (e.g., `pause`) to find the policy for the pause container.
3. The module enforces the rules in the container policy against the `config.json` (i.e., using either string- or regular-expression-based matching on each corresponding field).
4. If the enforcement passes, `kata-agent` proceeds with the container creation (i.e., passing the `config.json` (`oci`) as part of `opts` to `rustjail::LinuxContainer::new`).

If any of the above steps fail, `kata-agent` rejects the container creation.

# Implementation Plan

- Policy Format
  - [ ] Finalize the policy format
- Policy Generation
  - [ ] Implement the `cc-policy` crate that supports policy generation
  - [ ] Finalize the user experience
  - [ ] Define the infrastructure rules
- Policy Passing
  - [ ] Finalize the policy-passing mechanism
  - [ ] Support end-to-end policy passing
- Policy Attestation
  - [ ] Hypervisor exposes the MRCONFIGID (TDX) or HOSTDATA (SEV) option
        to the VM creation API
       - [ ] QEMU Support
       - [ ] Cloud-hypervisor support
  - [ ] `kata-shim` passes the policy digest as MRCONFIGID or HOSTDATA to the VM creation API
  - [ ] `kata-agent` validates the policy digest against the attestation report
  - [ ] Add the support of policy validation to the KBS or `attestation-service`
- Policy Enforcement
  - [ ] Implement the `cc-policy-enforcer` crate
  - [ ] Implement a plugin (rust-based or Rego) for the `cc-policy-enforcer` 
  - [ ] Integrate the `cc-policy-enforcer` with `kata-agent`
- Testing
  - [ ] Add unit tests
  - [ ] Add end-to-end tests
  - [ ] Enable CI tests (K8s integration and conformance tests)

# Discussion and Future Work

- Policy extensions

   With the mechanism of securely enforcing host-passed rules, the scope of the policy can be extended beyond the container metadata validation (also require extending the proposed policy syntax). Examples include
   - `kata-agent` gRPC interfaces
   - [Per-pod Kata configurations](https://github.com/kata-containers/kata-containers/blob/main/docs/how-to/how-to-set-sandbox-config-kata.md#per-pod-kata-configurations)
   - Customized fields for user data at either container or pod level

# Appendix

### Example of a policy

YAML
```
apiVersion: v1 
kind: Pod 
metadata: 
  name: test-pod
spec: 
  runtimeClassName: kata 
  containers: 
    - name: busybox
      image: busybox:latest
      command:
      - /bin/sh
      env:
      - name: CONTAINER_NAME
        value: "first-test-container"
      volumeMounts:
      - name: shared-data
        mountPath: /tmp
        readOnly: true
    - name: nginx 
      image: nginx:latest
      args:
          - sleep
          - "30"
      env:
      - name: POD_IP
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
      volumeMounts:
      - name: host-empty-vol
        mountPath: "/host/cache"
  volumes:
  - name: shared-data
    hostPath:
      path: /tmp
      type: Directory
  - name: host-empty-vol
    emptyDir: {}
```

Policy
```
{
  "version": "0.1.0",
  "containers": {
    "busybox": {
      "process": {
        "args": [
          "/bin/sh"
        ],
        "env": [
          "CONTAINER_NAME=first-test-container"
        ]
      },
      "mounts": [
        {
          "destination": "/tmp",
          "type": "bind",
          "source": "/tmp",
          "options": [
            "rbind",
            "rprivate",
            "ro"
          ]
        }
      ]
    },
    "nginx": {
      "process": {
        "args": [
          "sleep",
          "30"
        ],
        "env": [
          "POD_IP=^((25[0-5]|(2[0-4]|1\\d|[1-9]|)\\d).?\\b){4}$"
        ],
      },
      "mounts": [
        {
          "destination": "/host/cache",
          "type": "local",
          "source": "^/run/kata-containers/.+"
          "options": [
            "rbind",
            "rprivate",
            "rw"
          ]
        }
      ]
    }
  }
}
```

### Example of infrastructure rules

```
{
  "process": {
    "cwd": [
      "/"
    ],
    "env": [
      "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
      "^HOSTNAME=.+",
      "^[A-Z0-9_]+_SERVICE_HOST=^((25[0-5]|(2[0-4]|1\\d|[1-9]|)\\d).?\\b){4}$",
      "^[A-Z0-9_]+_SERVICE_PORT=[0-9]+",
      "^[A-Z0-9_]+_SERVICE_PORT_[A-Z]+=[0-9]+",
      "^[A-Z0-9_]+_PORT=[a-z]+://^((25[0-5]|(2[0-4]|1\\d|[1-9]|)\\d).?\\b){4}:[0-9]+",
      "^[A-Z0-9_]+_PORT_[0-9]+_[A-Z]+=[a-z]+://^((25[0-5]|(2[0-4]|1\\d|[1-9]|)\\d).?\\b){4}:[0-9]+",
      "^[A-Z0-9_]+_PORT_[0-9]+_[A-Z]+_PROTO=[a-z]+",
      "^[A-Z0-9_]+_PORT_[0-9]+_[A-Z]+_PORT=[0-9]+",
      "^[A-Z0-9_]+_PORT_[0-9]+_[A-Z]+_ADDR=^((25[0-5]|(2[0-4]|1\\d|[1-9]|)\\d).?\\b){4}$"
    ]
  },
  "mounts": [
    {
      "destination": "/proc",
      "source": "proc",
      "type": "proc",
      "options": [
        "nosuid",
        "noexec",
        "nodev"
      ]
    },
    {
      "destination": "/dev",
      "source": "tmpfs",
      "type": "tmpfs",
      "options": [
        "nosuid",
        "strictatime",
        "mode=755",
        "size=65536k"
      ]
    },
    {
      "destination": "/dev/pts",
      "source": "devpts",
      "type": "devpts",
      "options": [
        "nosuid",
        "noexec",
        "newinstance",
        "ptmxmode=0666",
        "mode=0620",
        "gid=5"
      ]
    },
    {
      "destination": "/dev/mqueue",
      "source": "mqueue",
      "type": "mqueue",
      "options": [
        "nosuid",
        "noexec",
        "nodev"
      ]
    },
    {
      "destination": "/dev/shm",
      "source": "/run/kata-containers/sandbox/shm",
      "type": "bind",
      "options": [
        "rbind"
      ]
    },
    {
      "destination": "/sys",
      "source": "sysfs",
      "type": "sysfs",
      "options": [
        "nosuid",
        "noexec",
        "nodev",
        "ro"
      ]
    },
    {
      "destination": "/etc/resolv.conf",
      "source": "/run/kata-containers/shared/containers/[a-z0-9]+-[a-z0-9]+-resolv.conf",
      "type": "bind",
      "options": [
        "rbind",
        "rprivate",
        "rw"
      ]
    },
    {
      "destination": "/etc/hostname",
      "source": "/run/kata-containers/shared/containers/[a-z0-9]+-[a-z0-9]+-hostname",
      "type": "bind",
      "options": [
        "rbind",
        "rprivate",
        "rw"
      ]
    },
    {
      "destination": "/etc/hosts",
      "source": "/run/kata-containers/shared/containers/[a-z0-9]+-[a-z0-9]+-hosts",
      "type": "bind",
      "options": [
        "rbind",
        "rprivate",
        "rw"
      ]
    },
    {
      "destination": "/dev/termination-log",
      "source": "/run/kata-containers/shared/containers/[a-z0-9]+-[a-z0-9]+-termination-log",
      "type": "bind",
      "options": [
        "rbind",
        "rprivate",
        "rw"
      ]
    },
    {
      "destination": "/var/run/secrets/kubernetes.io/serviceaccount",
      "source": "/run/kata-containers/shared/containers/[a-z0-9]+-[a-z0-9]+-serviceaccount",
      "type": "bind",
      "options": [
        "rbind",
        "rprivate",
        "ro"
      ]
    }
  ]
}
```
