### ISSUE TITLE
Roadmap to develop image sharing with integrity for CoCo

### ISSUE THREAD

**Issue by ChengyuZhu6** [confidential-containers/confidential-containers#141]
Image sharing with integrity was proposed in https://github.com/confidential-containers/confidential-containers/issues/137.  This issue is used to track the development of image sharing with integrity for CoCo.

snapshotter:

- [ ]  Define the format of `extraOption`(pass the block image and its verity information to kata-runtime/kata-agent/image-rs)
- [ ]  Download and process image
- [ ]  Export image as block device(s) with verity and return `Mount` array

kata-runtime:
- [ ]  Call `qemu` to share data from host to guest
- [ ]  Call `cloud-hypervisor` to share data from host to guest

kata-agent:
- [ ]  Call image-rs to handle data with `extraOption`
- [ ]  Validate and mount data with `extraOption` by self
- [ ]  Verity device management

kata-rootfs:
- [ ]  Install the dependencies with dm-verity

image-rs:
- [ ]  Integrity check with dm-verity and mount the data

The roadmap & task list can be updated then.
