### ISSUE TITLE
Roadmap to develop image pulling in the guest without forked containerd

### ISSUE THREAD

**Issue by ChengyuZhu6** [confidential-containers/confidential-containers#146]
Image pulling in the guest without forked containerd was proposed in https://github.com/confidential-containers/confidential-containers/issues/137. This issue is used to track the development of Image pulling in the guest without forked containerd.

snapshotter:

- [x]  Pass the image information to the `Mount` array
https://github.com/containerd/nydus-snapshotter/pull/499
https://github.com/containerd/nydus-snapshotter/pull/530

kata-agent: 
- [x]  Call Image-rs to pull image without passing pull image request.
https://github.com/kata-containers/kata-containers/pull/7676

tests:
- [x] tests for pulling image in the guest with nydus-snapshotter
https://github.com/kata-containers/tests/pull/5764

The roadmap & task list can be updated then.
